### ISSUE TITLE
What is missing to be production ready ?

### ISSUE THREAD

**Issue by sabativi** [cinn-labs/meteor-multitenancy#1]
Hello,

Just wondering what you had in mind when you wrote that it is not production ready ?

Thanks,

**Comment by ccstorch** [comment]
Hello @sabativi!

Maybe I should've been more clear on the description. 
I built this package for a specific project, so it may not be fully prepared for all cases, and also not well tested. I had a small timeline to build this, so it may have some bugs.

I've used in other 3 projects since then, and didn't have any problem.

I think "not production ready" was the wrong term to use it.

**Comment by sabativi** [comment]
Thanks for that answer
